# Generated by Django 3.1.3 on 2020-11-29 18:54

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=73)),
                ("large_content", models.TextField()),
                ("state", django_fsm.FSMField(default="draft", max_length=50)),
            ],
        ),
    ]
